### PR TITLE
updates to support django 3.2 

### PR DESCRIPTION
**Pull request by devfox-se**
Made some changes to support Django 2.2 and 3.2 LTS versions

### CODE REVIEW

**Comment by devfox-se** [comment]
@jcugat please have a look

**Comment by jcugat** [comment]
Hey @devfox-se, thanks for raising this! I'm in the process of upgrading the package to the latest best practices, so your PR comes perfectly timed!

**Comment by devfox-se** [comment]
@jcugat I'm glad you're still maintaining this package, thanks!

**Comment by jcugat** [comment]
Absolutely! Expect a new release soon with all the changes needed to support recent Django versions.

**Pull request merged**
