### PR TITLE
Instructions for Django 1.7+ to create migration

### PR DESCRIPTION
**Pull request by gsong**
As discussed in #20, since we can't reasonable include migrations, we should add instructions for Django 1.7+ users so they don't encounter errors when trying to spin up their app.

### CODE REVIEW

**Comment by jcugat** [comment]
I had an idea about the migrations that I want to try first. If it doesn't work I will merge this.

Thanks again for your help!

**Comment by derek73** [comment]
+1 this would be helpful to have in the readme

**Comment by benkonrath** [comment]
I have a potential solution for the migrations in #24.

**Comment by jcugat** [comment]
Finally managed to ship migrations. Thanks everybody for the help! Will release a new version soon™.

**Pull request closed without merging**
